version: '3.1'

services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
    working_dir: /app
    command: python main.py
    environment:
      - RABBIT_MQ=amqps://omfawpop:bdrSH1Ulb6kfw4wmq3xQfzGHMMTB4brA@albatross.rmq.cloudamqp.com/omfawpop
      - QUEUE_LISTENER_NAME=products.writer
    volumes:
      - ./:/app
