version: '3.1'

services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
    working_dir: /app
    command: python main.py
    environment:
      - RABBIT_MQ=****
      - QUEUE_LISTENER_NAME=products.writer
    volumes:
      - ./:/app
