version: '3.1'

services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
    working_dir: /app
    command: uvicorn --host 0.0.0.0 --port 8000 main:app --reload
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/gcp/hummy-app-cf80b50396b3.json
    volumes:
      - ./:/app
      - ../hummy-app-cf80b50396b3.json:/gcp/hummy-app-cf80b50396b3.json
    ports:
      - 8000:8000
